apiVersion: apps/v1
kind: Deployment
metadata:
  name:  hello-web
  namespace: default
  labels:
    app: {{ .Values.appname }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.appname }}
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 0%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Values.appname }}
    spec:
      containers:
      - name: hello-app
        image: oluwatoseen/hello-app:latest
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
          limits:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort:  80

---
apiVersion: v1
kind: Service
metadata:
  name: hello-web-service
  namespace: default
spec:
  selector:
    app: hello-app
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 80